Global:
  device: gpu
  seed: 1024

  global_batch_size: 24
  local_batch_size: 24
  micro_batch_size: 24


Engine:
  max_steps: 50
  num_train_epochs: 1
  auto_mode: full_rule_based
  logging_freq: 1
  test_iters:
  mix_precision:
    enable: False
    dtype: "float16"
    level: "o2"
    scale_loss: 32768.0
    custom_black_list: ["reduce_sum", "c_softmax_with_cross_entropy", "elementwise_div"]
    custom_white_list: ["lookup_table", "lookup_table_v2"]
  save_load:
    save_steps: 5
    output_dir: ./output
    ckpt_dir:


Model:
  module: "GPTModuleAuto"
  name: "GPT"
  vocab_size_divisible_unit: 128
  fuse_attn_qkv: True
  scale_qk_by_layer_num: True
  fused_softmax_with_triangular: True
  use_flash_attn: False
  sequence_parallel: False # TODO make sequence_parallel as an independent parallel and be set id Distributed
  vocab_size: 50304
  hidden_size: 256
  num_layers: 8
  num_attention_heads: 16
  ffn_hidden_size: 
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1
  max_position_embeddings: 1024
  type_vocab_size: 16
  initializer_range: 0.02
  use_recompute: False

Data:
  Train:
    collate_fn: gpt_collate_fn
    sample_split: 2
    dataset:
      name: GPTDataset
      input_dir: ./data/
      split: [969, 30, 1]
      max_seq_len: 1024

Optimizer:
  name: AdamW
  weight_decay: 0.01
  beta1: 0.9
  beta2: 0.999
  epsilon: 1.0e-8
  lr:
    name: CosineAnnealingWithWarmupDecay
    decay_steps: 360000
    warmup_rate: 0.01
    max_lr: 5.0e-5
    min_lr: 1.0e-5
    use_increments: True
  grad_clip:
    name: "ClipGradByGlobalNorm"
    clip_norm: 1.0


FusedPasses:
  fused_linear: False
  fused_adamw: False


Distributed:
  dp_degree: 1
  mp_degree: 8
  pp_degree: 2
  sharding:
    sharding_degree: 1
    sharding_stage: 1
